common: &common
  adapter: postgresql
  encoding: unicode
  database: backend_rails_development
  pool: 5
  username: nexusjs_rails
  password:

development:
  <<: *common
  database: backend_rails_development

test:
  <<: *common
  database: backend_rails_test

production:
  <<: *common
  database: backend_rails_production
