paths:
  jquery: "https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min"
  nexus: "nexus"
  commandHandlers: "registration/commandHandlers"
  eventHandlers: "registration/eventHandlers"
  routes: "registration/routes"