require([
	'jquery',
	'Nexus',
	'qunit',
	'tests/app/shouldDisplayMainScreenTest',
	'tests/app/shouldSayHelloTest',
	'tests/app/shouldSayItTest'
],function(
	$,
	Nexus,
	QUnit,
	shouldDisplayMainScreenTest,
	shouldSayHelloTest,
	shouldSayItTest
){
	$('#runTests').click(function () {	
		shouldDisplayMainScreenTest();
		shouldSayHelloTest();
		shouldSayItTest();	
	});
});